### ISSUE TITLE
Windows下如何做进程守护

### ISSUE THREAD

**Issue by DAMYSDS** [go-admin-team/go-admin#696]
请问Windows下如何做进程守护

**Comment by wenjianzhang** [comment]
可以做一个检测接口对外提供，外部系统心跳请求，实现健康检查，请求异常时报警就好了。

**Comment by wenjianzhang** [comment]
Hello @DAMYSDS, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](http://new-issue.ant.design) to create an issue, thank you!
你好 @DAMYSDS，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](http://new-issue.ant.design) 来创建 issue 以方便我们定位错误。谢谢配合！
