### ISSUE TITLE
字典数据模糊查找

### ISSUE THREAD

**Issue by wuqiufeng** [go-admin-team/go-admin#702]
**Describe the bug**
在字典列表添加job_status后,字典数据会自动关联sys_job_status的数据
**Expected behavior**
添加job_status后,job_status关联的数据为空

不需要进行模糊查找
dto/sys_dict_data.go文件
type SysDictDataGetPageReq struct {
	DictType       string `form:"dictType" search:"type:contains;column:dict_type;table:sys_dict_data" comment:""`
}

**Comment by wenjianzhang** [comment]
Hello @wuqiufeng, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @wuqiufeng，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！
