### ISSUE TITLE
我按照步骤来的 出现这个错误

### ISSUE THREAD

**Issue by GpsLypy** [go-admin-team/go-admin#709]
![image](https://user-images.githubusercontent.com/80027734/189054559-a12471e7-c038-4152-b035-434ec16e1bb9.png)

**Comment by wenjianzhang** [comment]
Hello @GpsLypy, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @GpsLypy，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！
