### ISSUE TITLE
使用命令没有将接口存到 sys_api 表

### ISSUE THREAD

**Issue by 2530442368** [go-admin-team/go-admin#713]
![image](https://user-images.githubusercontent.com/63909463/191587021-4c78b6ce-415f-4831-852a-6fa6c60c601a.png)
![image](https://user-images.githubusercontent.com/63909463/191587049-0228a702-a9d6-462d-b3a2-b1df24bf02ae.png)
![Y}P`N$~~Z`6Y8CUIFFGU0@B](https://user-images.githubusercontent.com/63909463/191588209-019735e9-c7e9-4936-967f-bfe2ce6ce30e.png)

**Comment by wenjianzhang** [comment]
Hello @2530442368, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @2530442368，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！
