### ISSUE TITLE
不通过命令运行 直接代码启动如何修改

### ISSUE THREAD

**Issue by shengyun1992** [go-admin-team/go-admin#714]
如何修改main.go的代码

**Comment by wenjianzhang** [comment]
Hello @shengyun1992, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @shengyun1992，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！
