### ISSUE TITLE
go-admin-ui项目npm run dev失败

### ISSUE THREAD

**Issue by xzknet** [go-admin-team/go-admin#715]
go-admin编译不通过。
在win10机器上，执行：npm run dev
编译无法通过

**Comment by wenjianzhang** [comment]
Hello @xzknet, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @xzknet，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！

**Comment by wenjianzhang** [comment]
https://doc.go-admin.dev/guide/ksks#%E9%AA%8C%E8%AF%81%E7%8E%AF%E5%A2%83
