### ISSUE TITLE
sys_user.salt 没有实际用到

### ISSUE THREAD

**Issue by yinquanyy** [go-admin-team/go-admin#721]
有个 BaseUser 用了 salt，但 BaseUser 也没有被引用

**Comment by wenjianzhang** [comment]
Hello @yinquanyy, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @yinquanyy，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！
