### ISSUE TITLE
初始化项目put请求会跨域

### ISSUE THREAD

**Issue by chenzhidongweb** [go-admin-team/go-admin#723]
get请求没事，put就不行，

**Comment by wenjianzhang** [comment]
Hello @chenzhidongweb, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://new-issue.go-admin.dev) to create an issue, thank you!
你好 @chenzhidongweb，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://new-issue.go-admin.dev) 来创建 issue 以方便我们定位错误。谢谢配合！
